# Define the goal
string action # move_base, pickup, place etc.
race_imagination/ParamList[] parameter # north, south, slow, medium, fast
race_imagination/WorldState world_state
race_imagination/RobotState robot_state
---
# Define the result: all fields are lists of lists
race_imagination/ParamList[] parameter # north, south, slow, medium, fast
race_imagination/DurationList[] durations
race_imagination/ConfidenceList[] confidences
---
